### MSSV: 20127508
### Tên: Bùi Quốc Hùng
### Lớp: 20CLC03

In [ ]:
import random 
import numpy as np
import pandas as pd

1

In [ ]:
# input m, n
m = int(input('Input m: '))
n = int(input('Input n: '))

Input m: 5
Input n: 3


In [ ]:
# print matrice beautifully
def print_mat(a):
  for i in range(len(a)):
    for j in range(len(a[0])):
      print(a[i][j], end='\t')
    print(end='\n')

In [ ]:
# generate a matrix which have random element from lim_u to lim_d
lim_d = 10
lim_u = -10 
def generate_random_mat(m, n):
  result = [[random.randint(lim_u, lim_d) for j in range(n)] for i in range(n)]
  return result
P = generate_random_mat(n, n) # n x n matrix

In [ ]:
print_mat(P)

-3	-9	-3	
-10	0	-6	
-5	-10	2	


In [ ]:
# create identity matrix
def identity_mat(n):
  mat = [[0 for j in range(n)] for i in range(n)]# np.zeros((m, h))
  for i in range(0, n):
    mat[i][i] = 1
  return np.array(mat)


# matrix power function
def power_mat(mat, n):
    accu = identity_mat(len(mat))
    for i in range(n):
      accu = np.dot(accu, mat)
    return accu
  



In [ ]:
P_pm = power_mat(P, m)

In [ ]:
print_mat(P_pm)

-292068	-321879	-141987	
-354600	-234990	-196326	
-245775	-322645	-110203	


In [ ]:
dir = '/content/weights.csv' # read the weight.csv from subfolder  /content/weights.csv
df = pd.read_csv(dir) # change directory here to your directory 

In [ ]:
df

ID  weight  length  headc
0    L001    3.95    55.5   37.5
1    L003    4.63    57.0   38.5
2    L004    4.75    56.0   38.5
3    L005    3.92    56.0   39.0
4    L006    4.56    55.0   39.5
..    ...     ...     ...    ...
545  W319    5.35    57.0   39.5
546  W320    5.39    60.0   40.0
547  W321    3.88    52.0   36.0
548  W322    5.23    57.5   40.0
549  W323    4.57    53.5   37.5

[550 rows x 4 columns]

In [ ]:
df.describe()

weight      length       headc
count  550.000000  550.000000  550.000000
mean     4.366418   54.840909   37.895273
std      0.601822    2.406908    1.361564
min      2.920000   48.000000   34.000000
25%      3.950000   53.000000   37.000000
50%      4.330000   55.000000   38.000000
75%      4.770000   56.500000   39.000000
max      6.490000   62.000000   41.200000

In [ ]:
df['ID'].count()

550

In [ ]:
# detach the Y - training_labels and X - training_set
training_labels = df['weight'].copy().to_numpy()
training_set = df.drop(columns = ['ID', 'weight']).copy().to_numpy()

In [ ]:
training_set

array([[55.5, 37.5],
       [57. , 38.5],
       [56. , 38.5],
       ...,
       [52. , 36. ],
       [57.5, 40. ],
       [53.5, 37.5]])

In [ ]:
training_labels

array([3.95, 4.63, 4.75, 3.92, 4.56, 3.64, 3.55, 4.53, 4.97, 3.74, 4.19,
       4.35, 4.62, 4.09, 4.42, 5.62, 5.25, 4.32, 4.41, 4.18, 4.29, 4.67,
       3.97, 4.57, 4.53, 4.18, 4.78, 3.72, 4.53, 4.46, 4.11, 4.  , 3.42,
       4.95, 3.3 , 4.52, 4.07, 4.54, 4.05, 3.34, 4.77, 4.21, 4.26, 3.88,
       4.36, 4.65, 5.4 , 3.9 , 4.24, 3.74, 3.7 , 4.34, 4.61, 4.6 , 4.89,
       3.69, 4.47, 5.14, 4.77, 4.5 , 5.34, 3.53, 5.02, 5.02, 5.45, 5.81,
       3.66, 3.34, 4.2 , 4.6 , 4.84, 3.96, 4.26, 3.51, 4.62, 5.69, 4.52,
       3.11, 3.79, 4.01, 3.54, 4.48, 4.92, 4.93, 3.9 , 4.09, 4.59, 4.39,
       4.99, 4.18, 4.12, 3.79, 3.99, 4.62, 3.48, 4.9 , 4.26, 4.88, 4.06,
       4.27, 4.68, 4.03, 4.1 , 4.86, 4.7 , 3.77, 4.01, 4.47, 4.78, 4.22,
       4.73, 4.39, 4.6 , 4.15, 3.74, 3.95, 3.88, 5.11, 3.05, 3.45, 4.52,
       3.82, 4.4 , 3.79, 5.02, 5.2 , 4.74, 3.77, 4.27, 4.41, 5.55, 4.08,
       3.59, 5.03, 3.85, 4.01, 4.91, 5.13, 4.98, 4.32, 4.27, 5.54, 4.35,
       4.53, 4.92, 3.8 , 3.89, 3.96, 3.85, 3.9 , 5.

In [ ]:
# generate X to calculate the coefficient, there are 4 functions in my work for the requirements
def generateX(X, prob=0): 
  vars = []

  if prob == 0:
    X_0 = np.array([1 for i in range(X.shape[0])])
    vars.append(X_0)
    
    X_1 = np.array([i for i in X[:, 0]]) 
    vars.append(X_1)



  if prob == 1:
    X_0 = np.array([1 for i in range(X.shape[0])])
    vars.append(X_0)

    X_2 = np.array([i for i in X[:, 1]]) 
    vars.append(X_2)


  if prob == 2:
    X_0 = np.array([1 for i in range(X.shape[0])])
    
    vars.append(X_0)
    
    X_1 = np.array([i for i in X[:, 0]]) 
    vars.append(X_1)

    X_2 = np.array([i for i in X[:, 1]]) 
    vars.append(X_2)

    


  #---------------------------------

  if prob == 3:
    X_0 = np.array([1 for i in range(X.shape[0])])
    
    vars.append(X_0)
    
    X_1 = np.array([i for i in X[:, 0]]) 
    vars.append(X_1)

    X_2 = np.array([i for i in X[:, 1]]) 
    vars.append(X_2)

    X_3 = X_1 * X_2  
    vars.append(X_3)

  



  #---------------------------------

  if prob == 4:
    X_0 = np.array([1 for i in range(X.shape[0])])
    
    vars.append(X_0)
    
    X_1 = np.array([i**2 for i in X[:, 0]]) 
    vars.append(X_1)

    X_2 = np.array([i for i in X[:, 1]]) 
    vars.append(X_2)

    # X_3 = X_1 * X_2  
    # vars.append(X_3)

  return np.stack(vars).T
def generateY(Y):
  return Y.T

In [ ]:
# calculate theta through the formula
def cal_theta(X,Y, kind=0):
  A = generateX(X, kind)
  B = generateY(Y)
  theta = np.linalg.inv(A.T @ A) @ (A.T @ B)
  return theta

In [ ]:
# calculate the rss 
def cal_r_rss(theta, X, Y, kind=0):

  A = generateX(X, kind)
  B = generateY(Y)



  r = A @ theta - B
  rss = np.sum(r * r)


  return r, rss       

In [ ]:
X = training_set.copy()
Y = training_labels.copy()

b1 

In [ ]:
kind = 0

theta = cal_theta(X, Y, kind)
r, r_norm = cal_r_rss(theta, X, Y, kind)

print(theta.T)
print(r_norm)

[-5.41214476  0.17830782]
97.72301717340707


In [ ]:
kind = 1

theta = cal_theta(X, Y, kind)
r, r_norm = cal_r_rss(theta, X, Y, kind)

print(theta.T)
print(r_norm)

[-6.05986673  0.27513418]
121.79803049315558


In [ ]:
kind = 2

theta = cal_theta(X, Y, kind)
r, r_norm = cal_r_rss(theta, X, Y, kind)

print(theta.T)
print(r_norm)

[-8.01868279  0.13268373  0.13480849]
85.8471198337366


b2

In [ ]:
kind = 3

theta = cal_theta(X, Y, kind)
r, r_norm = cal_r_rss(theta, X, Y, kind)

print(theta.T)
print(r_norm)

[-1.22651649e+01  2.10459990e-01  2.46563676e-01 -2.04494604e-03]
85.81756053333928


b3

In [ ]:
print(X)

[[55.5 37.5]
 [57.  38.5]
 [56.  38.5]
 ...
 [52.  36. ]
 [57.5 40. ]
 [53.5 37.5]]


In [ ]:
kind = 4

theta = cal_theta(X, Y, kind)
r, r_norm = cal_r_rss(theta, X, Y, kind)

print(theta.T)
print(r_norm)

[-4.38815643e+00  1.20164110e-03  1.35469664e-01]
85.81549408786184


In [ ]:
l = int(input('Input the length of baby: '))
c = int(input('Input the circumference of baby : '))

Input the length of baby: 57
Input the circumference of baby : 38


In [ ]:
X_inf = np.array([[l, c]])

In [ ]:
A = generateX(X_inf, kind)

In [ ]:
pred = A @ theta 

In [ ]:
print(f'My weight prediction for the baby is {pred[0]} kg')

My weight prediction for the baby is 4.663822767296928 kg
